# Generated by Django 5.1.2 on 2024-10-25 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_manager', '0002_rename_query_detectionrule_rule_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edithistory',
            name='action_type',
            field=models.CharField(choices=[('create', 'Criação'), ('edit', 'Edição'), ('delete', 'Deleção')], default='create', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detectionrule',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_rules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edithistory',
            name='changed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
