# Generated by Django 5.1.2 on 2024-10-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_manager', '0003_edithistory_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrule',
            name='rule_data',
            field=models.TextField(),
        ),
    ]
