# Generated by Django 5.1.2 on 2024-10-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_manager', '0004_alter_detectionrule_rule_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrule',
            name='rule_data',
            field=models.TextField(default='{}'),
        ),
    ]
